print_info() {
    info title
    info underline
    info "OS" distro
    info "Host" model
    info "Kernel" kernel
    info "Uptime" uptime
    info "Packages" packages
    info "Shell" shell
    info "Terminal" term
    info "CPU" cpu
    info "Memory" memory
    info "Disk" disk
    info cols
}

memory_percent="on"
disk_show=("/")
disk_subtitle="mount"
ascii_distro="auto"
